service: aws-node-express-dynamodb-api-project
frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: '*'

# ENABLE TYPESCRIPT

plugins:
  - serverless-plugin-typescript

# CLOUD FORMATION CONFIGURATION

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        # BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
        ProvisionedThroughput: # ADDED LINE FOR BILLING OPTIMIZATION
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
