/* tslint:disable */
/* eslint-disable */
/**
 * Game-Player Manager Service
 * This service provides endpoints for all game-player manager related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateGameDto
 */
export interface CreateGameDto {
  /**
   * Game name
   * @type {string}
   * @memberof CreateGameDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateGameDto
   */
  description?: string;
  /**
   * Maximum game-play score for a game
   * @type {number}
   * @memberof CreateGameDto
   */
  maxGamePlayScore: number;
  /**
   * Maximum game-play score submission count for a game (players are not allowed to submit more than the given value)
   * @type {number}
   * @memberof CreateGameDto
   */
  dailyMaxScoreSubmissionCount: number;
}
