/* tslint:disable */
/* eslint-disable */
/**
 * Game-Player Manager Service
 * This service provides endpoints for all game-player manager related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Game
 */
export interface Game {
    /**
     * 
     * @type {string}
     * @memberof Game
     */
    id: string;
    /**
     * Game name
     * @type {string}
     * @memberof Game
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Game
     */
    description?: string;
    /**
     * Maximum game-play score for a game
     * @type {number}
     * @memberof Game
     */
    maxGamePlayScore: number;
    /**
     * Maximum game-play score submission count for a game (players are not allowed to submit more than the given value)
     * @type {number}
     * @memberof Game
     */
    dailyMaxScoreSubmissionCount?: number;
    /**
     * Date & time game record was created
     * @type {string}
     * @memberof Game
     */
    createdAt?: string;
}
