/* tslint:disable */
/* eslint-disable */
/**
 * Game-Player Manager Service
 * This service provides endpoints for all game-player manager related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * List of human genders
 * @export
 * @enum {string}
 */
export enum Gender {
    MALE = 'MALE',
    GEMALE = 'GEMALE',
    OTHERS = 'OTHERS'
}

 