/* tslint:disable */
/* eslint-disable */
/**
 * Game-Player Manager Service
 * This service provides endpoints for all game-player manager related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Gender } from './gender';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * User unique identifier
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * User's username in platform
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isAdmin: boolean;
    /**
     * 
     * @type {Gender}
     * @memberof User
     */
    gender?: Gender;
    /**
     * User biography (information about user)
     * @type {string}
     * @memberof User
     */
    bio?: string;
}
